# Criar Usuário
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "João Silva",
  "email": "joao.silva@example.com"
}

###

# Listar Usuários
GET http://localhost:3000/usuarios

###

# Buscar Usuário por ID
GET http://localhost:3000/usuarios/1

###

# Atualizar Usuário
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
  "nome": "João Atualizado",
  "email": "joao.atualizado@example.com"
}

###

# Excluir Usuário
DELETE http://localhost:3000/usuarios/1
