# Criar Usuário
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nome": "PEDRO Silva",
  "email": "pedro.silva@example.com"
}

###

# Listar Usuários
GET http://localhost:3000/usuarios

###

# Buscar Usuário por ID
GET http://localhost:3000/usuarios/1

###

# Atualizar Usuário
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
  "nome": "João Atualizado",
  "email": "joao.atualizado@gmail.com"
}

###

# Excluir Usuário
DELETE http://localhost:3000/usuarios/2


### 

# Login 
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "gustavo123@gmail.com",
  "senha": "gustavo123"
}
